---
title: ""
output:
  github_document:
    toc: true
---

## Introduction


```{r setup, include=FALSE}
# Load libraries
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(GREAT)
library(readxl)
```

```{r}
caco_h2o2 <- readxl::read_xlsx("~/PhD/main_phd/genalignR_development/data_briede_et_all_2010_colon_cancer/exposure_h2o2.xlsx")
caco_menadione <- readxl::read_xlsx("~/PhD/main_phd/genalignR_development/data_briede_et_all_2010_colon_cancer/exposure_menadione.xlsx")
```

### Processing H2O2 exposured data

```{r}
caco_h2o2 <- caco_h2o2 %>% 
  tidyr::pivot_longer(!GeneSymbol, names_to = "timepoint", values_to = "expression_value") %>% 
  dplyr::mutate(timepoint = as.numeric(stringr::str_remove_all(timepoint, "h")), 
                accession = "h202", 
                tissue = "colon", 
                group = 1
  ) %>% 
  dplyr::rename(locus_name = GeneSymbol)
```


### Processing menadione exposured data

```{r}
caco_menadione <- caco_menadione %>% 
  tidyr::pivot_longer(!GeneSymbol, names_to = "timepoint", values_to = "expression_value") %>% 
  dplyr::mutate(timepoint = as.numeric(stringr::str_remove_all(timepoint, "h")), 
                accession = "menadione", 
                tissue = "colon", 
                group = 1
  ) %>% 
  dplyr::rename(locus_name = GeneSymbol)
```

### Combine data and select only common genes 

```{r}
common_genes <- intersect(caco_h2o2$locus_name, caco_menadione$locus_name) %>% unique()# %>% head(40)

# Combine together all of data
caco_all <- dplyr::bind_rows(caco_h2o2, caco_menadione)

# Select only first common genes 
caco_all_common_genes <- caco_all %>% 
  dplyr::filter(locus_name %in% common_genes)

common_genes %>% length()
```

### Plot data

```{r fig.width=25, fig.height=60, warning=FALSE}
caco_all_common_genes %>%
  ggplot2::ggplot() +
  ggplot2::aes(y = expression_value, x = timepoint, group = accession, color = accession) +
  # ggplot2::stat_summary(fun = mean, geom = "line", size = 1) +
  # ggplot2::stat_summary(
  #       fun.data = ggplot2::mean_se,
  #       fun.args = list(mult = 1),
  #       geom = "ribbon",
  #       color = NA,
  #       alpha = 0.3
  #     ) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~locus_name, scales = "free", ncol = 4) 
```


## Register genes

```{r}
# Find the approximation of stretch factor 
GREAT::get_approximate_stretch(caco_all_common_genes, "h202", "menadione")
```

```{r caco-reg-results}
caco_reg_results <- scale_and_register_data(
  input_df = caco_all_common_genes,
  # input_df = caco_all_common_genes %>% 
  #   dplyr::filter(
  #     locus_name %in% c("ABCC3", "C20orf149", "C6orf1")
  # ),
  stretches = seq(0.8, 1.3, 0.1),
  shift_extreme = 5,
  num_shifts = 21,
  min_num_overlapping_points = 4,
  initial_rescale = TRUE,
  do_rescale = TRUE,
  accession_data_to_transform = "menadione",
  accession_data_ref = "h202",
  start_timepoint = "reference", 
  expression_value_threshold = NULL
)
```

```{r}
caco_reg_results$imputed_mean_df %>% 
  dplyr::filter(locus_name == "ZNF133") %>% 
  plot_registered_gene_of_interest()
```






