---
title: "Running all of gene-registration functions for limited B. Rapa"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(GREAT)
library(ggplot2)
library(data.table)
```

## Background

Running gene-registration functions for limited `B. Rapa` genes to understand more about what output to expect for each function, especially during shifting and stretching processes. (Since next I want to run with `B. Oleracea` genes.)


```{r}
id_table_path <- system.file("extdata/sample_data/id_table.RDS", package = "GREAT")
arabidopsis_expression_path <- system.file("extdata/sample_data/arabidopsis_expression.RDS", package = "GREAT")
brassica_rapa_expression_path <- system.file("extdata/sample_data/brassica_rapa_expression.RDS", package = "GREAT")
list_gene_of_interest <- c("AT1G69120", "AT5G61850", "AT2G45660")

new_mean_data <- load_mean_df(file_path_brassica = brassica_rapa_expression_path, 
                              file_path_arabidopsis = arabidopsis_expression_path, 
                              file_path_id_table = id_table_path, 
                              tissue_wanted = "apex", 
                              curr_GoIs = list_gene_of_interest, 
                              sum_brassicas = F)
```

```{r}
do.initial.rescale <- 'nope' # should be 'rescale' if want to use scaled df for registration, rather than mean_df
do.register.rescale <- 'rescale' 
outdir.string <- 'TESTING_rescale_as_register___shuffled_g_v4__'
```

```{r}
# calculate the scores associated with each candidate shift
# Arabidopsis observations = 7d -> 16d = 0d -> 9d
# Ro18 observations = 11d -> 35d = 0d -> 24d
# therefore if same start and end points stretch = 24 / 9

# lots of spurious overlaps detected when too extreme shifts allowed
stretch = c(2, 1.5, 1)
min_num_overlapping_points = 4
shift_extreme  = 4
transformed.timecourse = 'Col0'
num.shuffled <- 1
jobNum <- 1
```

## Run scripts

```{r}
# setup flags for rescaling options
if (do.initial.rescale=='rescale') {
  initial.rescale <- TRUE
} else {
  initial.rescale <- FALSE
}
if (do.register.rescale=='rescale') {
  should.rescale <- TRUE
} else {
  should.rescale <- FALSE
}

if (initial.rescale==TRUE) {
  print('********************')
  print('will rescale the data prior to registering, and register using this rescaled mean data!')
  print('********************')
}
if (should.rescale==TRUE){
  print('********************')
  print('will rescale the data when deciding optimal registration!')
  print('********************')
} 
```

```{r}
# directories to save graphs to
real.data.graph.dir <- paste0('graphs/gene_registration/', outdir.string, '_real_data/')
# shuffled.data.graph.dir <- paste0('graphs/gene_registration/', outdir.string, '_shuffled_data/job_', jobNum, '/')
# directories to save real and shuffled expression data to
real.expression.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_data/gene_expression/job_', jobNum, '/')
shuffled.expression.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_shuffled_data/gene_expression/')
# directories to save real and shuffled distance data to
real.distance.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_distance/job_', jobNum, '/')
shuffled.distance.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_shuffled_distance/')
  

# somewhere to store the data.tables and graphs
if (!(dir.exists(real.expression.dir))) {
    dir.create(real.expression.dir, recursive=T)
    dir.create(shuffled.expression.dir, recursive=T)
    
    dir.create(real.distance.dir, recursive=T)
    dir.create(shuffled.distance.dir, recursive=T)

    dir.create(real.data.graph.dir, recursive=T)
    # dir.create(shuffled.data.graph.dir, recursive=T)
}
```

```{r}
## GET THE RAW DATA. MEAN EXPRESSION OF BIOLOGICAL REPS. TREAT BRASSICA GENES INDIVIDUALLY (DON'T SUM THEM).
# load the data expression data. Consider the brassica genes individually (don't sum)
# L <- load_mean_df() # sumBrassica copy flag is within load_mean_df()
mean_df <- new_mean_data[[1]] # will compare Col0 vs Ro18 based on accession column
all.data.df <- new_mean_data[[2]]
```

```r
mean_df <- mean_df %>% 
  dplyr::mutate(accession = ifelse(accession == "Ro18", "DH", "Col0"))

all.data.df <- all.data.df %>% 
  dplyr::mutate(accession = ifelse(accession == "Ro18", "DH", "Col0"))
```

```{r}
mean_df
```



```{r}
## PREPARE, AND REGISTER AND SCALE THE DATA
O <- prepare_scaled_and_registered_data(mean_df, all.data.df,
  stretch = stretch, initial.rescale, should.rescale, min_num_overlapping_points,
  shift_extreme, transformed.timecourse
)
```

```{r}
mean_df 
```




```{r start test get_extreme shift}
# Make input data name as it is inside the function
test <- mean_df
stretch_factor <- stretch
stretch_factor

curr_sym <- unique(test$locus_name)[1]
curr_sym

test <- test[test$locus_name==curr_sym, ]
test
```

```{r}
# transform timepoint to be time from first timepoint
test[, delta_time:=timepoint - min(timepoint), by=.(accession)]
test
```

```{r}
ggplot(test[test$locus_name=='BRAA02G018970.3C',],
       aes(x=delta_time, y=mean.cpm, color=accession))+
  geom_point()+
  geom_line()
```


```{r}
# apply stretch_factor to the arabidopsis, leave the rapa as is
test$delta_time[test$accession=='Col0'] <- test$delta_time[test$accession=='Col0'] * 4

test
```

```{r}
ggplot(test[test$locus_name=='BRAA02G018970.3C',],
       aes(x=delta_time, y=mean.cpm, color=accession))+
  geom_point()+
  geom_line()
```




```{r}
M <- calc_extreme_shifts(test, min_num_overlapping_points, shift_extreme)

M
```

```{r}
original <- data.table::copy(test)
original$shifted_time <- original$delta_time

  # print('line 1803')
  # print(original)

  # -ve extreme shift will be -1*exactly the difference between 1 of the stretched Col0 timepoints, and the smallest Ro18 timepoint
  # +ve extreme will be the difference between 1 of the col0 timepoints, and the maximum Ro18 timepoint
neg_extreme_candidate <- -1*(original$delta_time[original$accession=='Col0'] - min(original$delta_time[original$accession=='Ro18']))


pos_extreme_candidates <- max(original$delta_time[original$accession=='Ro18']) - original$delta_time[original$accession=='Col0']
```

```{r}
neg_extreme_candidate
```

```{r}
pos_extreme_candidates
```


```{r}
num.overlapping.points <- sapply(neg_extreme_candidate, FUN=calc_num_overlapping_points, original=original)

num.overlapping.points
```

```{r}
neg.extreme <- min(neg_extreme_candidate[num.overlapping.points >= min_num_overlapping_points])
neg.extreme

num.overlapping.points <- sapply(pos_extreme_candidates, FUN=calc_num_overlapping_points, original=original)
neg.extreme <- max(pos_extreme_candidates[num.overlapping.points >= min_num_overlapping_points])
neg.extreme
```

