---
title: "Running all of gene-registration functions for limited (key floral) genes in *B. Oleracea*"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set()
library(GREAT)
library(ggplot2)
library(data.table)
library(cowplot)
library(ggpubr)
```

```{r function, include=FALSE}
plot_goI_expression <- function(summed.GoIs.df) {
  # make plot of gene expression in Col0, and in Ro18.
  morphology.equiv.df <- data.frame('accession'=c('Col-0', 'DH'), 'floral.transition.time'=c(14, 35))
  summed.GoIs.df$accession <- as.character(summed.GoIs.df$accession)
  summed.GoIs.df$accession[summed.GoIs.df$accession=='Col0'] <- 'Col-0'
  summed.GoIs.df$accession[summed.GoIs.df$accession=='Ro18'] <- 'DH'

  curr.acc <- 'Col-0'
  plot.list <- list()
  for (curr.acc in c('Col-0', 'DH')) {

    curr.p <- ggplot(summed.GoIs.df[summed.GoIs.df$accession==curr.acc,],
                     aes(x=timepoint, y=mean.cpm, color=Ara.name, fill=Ara.name))+
      geom_vline(data=morphology.equiv.df[morphology.equiv.df==curr.acc,], aes(xintercept=floral.transition.time), size=1)+
      stat_summary(fun=mean, geom='line', size=1)+
      # stat_summary(fun.data=mean_se, fun.args=list(mult=1.96),geom='ribbon',color=NA, alpha=0.3)+
      # https://stackoverflow.com/questions/19258460/standard-error-bars-using-stat-summary
      # https://www.ling.upenn.edu/~joseff/rstudy/summer2010_ggplot2_intro.html
      # option1
      stat_summary(fun.data = mean_cl_normal, geom = 'ribbon', fun.args = list(mult = 1), alpha=0.3, color = NA) +
      # option2
      # stat_summary(fun.data=mean_se, geom='ribbon', color=NA, alpha=0.3) +
      geom_point(size=0.4)+
      facet_wrap(~accession, ncol=1, scales='free')+
      scale_x_continuous(breaks=scales::pretty_breaks())+
      theme_bw()+
      ylab('expression (cpm)')+
      xlab('timepoint (d)')+
      guides(fill=guide_legend(nrow=2,byrow=TRUE),
             color=guide_legend(nrow=2,byrow=TRUE))+
      theme(legend.position='top',
            legend.title = element_blank(),
            legend.text = element_text(face='italic', size=8),
            axis.title = element_text(size=10),
            axis.text=element_text(size=6),
            legend.margin=margin(0,0,-10,0))

    leg <- get_legend(curr.p)
    leg.plot <- as_ggplot(leg)
    leg.plot + theme(plot.margin=c(0,0,0,0))

    curr.p <- curr.p + theme(legend.position='none')

    if (curr.acc == 'Col-0') {
      curr.p <- curr.p + theme(axis.title.x=element_blank())+
        coord_cartesian(ylim=c(0, 250))
    }

    plot.list <- c(plot.list, list(curr.p))
  }
  plot.list <- c(list(leg.plot), plot.list)
  p.grid <- plot_grid(plotlist=plot.list, rel_heights = c(0.3,0.93,1), ncol=1, align='v')

  return(p.grid)
}

plot_goI_expression_scaled <- function(summed.GoIs.df) {

  # make plot of gene expression in Col0, and in Ro18.
  # truncate data so can see expression nicely on the same scale
  # summed.GoIs.df <- summed.GoIs.df[summed.GoIs.df$timepoint <=21,]

  summed.GoIs.df[, scaled.cpm:=my.scale(mean.cpm), by=.(Ara.id, accession)]
  morphology.equiv.df <- data.frame('accession'=c('Col-0', 'DH'), 'floral.transition.time'=c(14, 35))
  summed.GoIs.df$accession <- as.character(summed.GoIs.df$accession)
  summed.GoIs.df$accession[summed.GoIs.df$accession=='Col0'] <- 'Col-0'
  summed.GoIs.df$accession[summed.GoIs.df$accession=='Ro18'] <- 'DH'

  curr.acc <- 'Col-0'
  plot.list <- list()
  for (curr.acc in c('Col-0', 'DH')) {

    curr.p <- ggplot(summed.GoIs.df[summed.GoIs.df$accession==curr.acc,],
                     aes(x=timepoint, y=scaled.cpm, color=Ara.name, fill=Ara.name))+
      #geom_vline(data=summed.GoIs.df[summed.GoIs.df$accession=='Col-0' & summed.GoIs.df$accession==curr.acc,], aes(xintercept=floral.transition.time), size=1)+
      #geom_vline(data=summed.GoIs.df[summed.GoIs.df$accession=='R-O-18' & summed.GoIs.df$accession==curr.acc,,], aes(xintercept=floral.transition.time), size=1)+
      geom_vline(data=morphology.equiv.df[morphology.equiv.df==curr.acc,], aes(xintercept=floral.transition.time), size=1)+

      stat_summary(fun=mean, geom='line', size=1)+
      stat_summary(fun.data=mean_se, fun.args=list(mult=1.96), geom='ribbon',
                   color=NA, alpha=0.3)+
      geom_point(size=0.4)+
      facet_wrap(~accession, ncol=1, scales='free')+
      scale_x_continuous(breaks=scales::pretty_breaks())+
      theme_bw()+
      ylab('expression (cpm)')+
      xlab('timepoint (d)')+
      guides(fill=guide_legend(nrow=2,byrow=TRUE),
             color=guide_legend(nrow=2,byrow=TRUE))+
      theme(legend.position='top',
            legend.title = element_blank(),
            legend.text = element_text(face='italic', size=8),
            axis.title = element_text(size=10),
            axis.text=element_text(size=6),
            legend.margin=margin(0,0,-10,0))

    leg <- get_legend(curr.p)
    leg.plot <- as_ggplot(leg)
    leg.plot + theme(plot.margin=c(0,0,0,0))

    curr.p <- curr.p + theme(legend.position='none')

    if (curr.acc == 'Col-0') {
      curr.p <- curr.p + theme(axis.title.x=element_blank())
    }

    plot.list <- c(plot.list, list(curr.p))
  }
  plot.list <- c(list(leg.plot), plot.list)
  p.grid <- plot_grid(plotlist=plot.list, rel_heights = c(0.3,0.93,1), ncol=1, align='v')

  return(p.grid)
}
plot_registered_GoIs_for_comparible_timepoints <- function(all.stretched.df) {

  # make plot of gene expression after registration - only plot compared timepoints
  # cut down to compared timepoints for each gene

  registered.plot.df <- all.stretched.df
  AGL24.df <- registered.plot.df[registered.plot.df$locus_name=='AGL24'] #&
                                   # (registered.plot.df$shifted.time <=35) &
                                   # (registered.plot.df$shifted.time >=13),]
  AP1.df <- registered.plot.df[registered.plot.df$locus_name=='AP1'] #&
                                 # (registered.plot.df$shifted.time <=25) &
                                 # (registered.plot.df$shifted.time >=11),]
  AP3.df <- registered.plot.df[registered.plot.df$locus_name=='AP3'] #&
                                 # (registered.plot.df$shifted.time <=25) &
                                 # (registered.plot.df$shifted.time >=13),]
  LFY.df <- registered.plot.df[registered.plot.df$locus_name=='LFY'] #&
                                 # (registered.plot.df$shifted.time <=19) &
                                 # (registered.plot.df$shifted.time >=10),]
  SOC1.df <- registered.plot.df[registered.plot.df$locus_name=='SOC1'] #&
                                  # (registered.plot.df$shifted.time <=31) &
                                  # (registered.plot.df$shifted.time >=10),]
  SPL8.df <- registered.plot.df[registered.plot.df$locus_name=='SPL8']
  SVP.df <- registered.plot.df[registered.plot.df$locus_name=='SVP']
  SPL5.df <- registered.plot.df[registered.plot.df$locus_name=='SPL5']
  registered.plot.df <- rbind(AGL24.df, AP1.df, AP3.df, LFY.df, SOC1.df, SPL8.df, SVP.df, SPL5.df)

  registered.plot.df$accession <- as.character(registered.plot.df$accession)
  registered.plot.df$accession[registered.plot.df$accession=='Col0'] <- 'Col-0'
  registered.plot.df$accession[registered.plot.df$accession=='Ro18'] <- 'DH'

  p.registered <- ggplot(registered.plot.df, aes(x=shifted.time, y=mean.cpm, color=accession, fill=accession))+
    stat_summary(fun=mean, geom='line', size=1)+
    stat_summary(fun.data=mean_se, fun.args=list(mult=1.96),geom='ribbon',
                 color=NA, alpha=0.3)+
    geom_point(size=0.4)+
    theme_bw()+
    xlab('registered time (d)')+
    ylab('normalised expression')+
    facet_wrap(~locus_name, scales='free', ncol=2)+
    scale_x_continuous(breaks=scales::pretty_breaks())+
    # scale_color_brewer(palette = "Set2", direction = 1) +
    # scale_fill_brewer(palette = "Set2", direction = 1) +
    theme(legend.position = 'top',
          legend.title = element_blank(),
          axis.title = element_text(size=10),
          axis.text=element_text(size=6),
          strip.text=element_text(face='italic'),
          legend.margin=margin(21,0,0,0))

  return(p.registered)
}

plot_registered_GoIs_for_comparible_timepoints_new <- function(registered.plot.df) {

  registered.plot.df$accession <- as.character(registered.plot.df$accession)
  registered.plot.df$accession[registered.plot.df$accession=='Col0'] <- 'Col-0'
  registered.plot.df$accession[registered.plot.df$accession=='Ro18'] <- 'DH'

  p.registered <- ggplot(registered.plot.df, aes(x=shifted.time, y=mean.cpm, color=accession, fill=accession))+
    stat_summary(fun=mean, geom='line', size=1)+
    stat_summary(fun.data=mean_se, fun.args=list(mult=1.96),geom='ribbon',
                 color=NA, alpha=0.3)+
    geom_point(size=0.4)+
    theme_bw()+
    xlab('registered time (d)')+
    ylab('normalised expression')+
    facet_wrap(~locus_name, scales='free', ncol=2)+
    scale_x_continuous(breaks=scales::pretty_breaks())+
    theme(legend.position = 'top',
          legend.title = element_blank(),
          axis.title = element_text(size=10),
          axis.text=element_text(size=6),
          strip.text=element_text(face='italic'),
          legend.margin=margin(21,0,0,0))

  return(p.registered)
}

```

## Background

In this Rmd, I ran gene registration functions for *B. Oleracea* key floral genes. 


## Get all of data 

```{r}
# Get all of the data path
table_id_path <- "/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/ID_TAB.csv"
ara_path <- '/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/klepikova.rds'
b_oleracea_path <- "/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/dh_with_sample_id.rds"
```

```{r}
table_id_info_key_floral_genes <- data.table::fread(table_id_path) %>% 
  dplyr::filter(symbol %in% c("SOC1", "AP1", "AP3", "AGL24", "LFY", "SPL8", "SVP", "SPL5")) %>% 
  dplyr::select(CDS.model, symbol, locus_name) %>% 
  unique() %>% 
  dplyr::arrange(symbol)


table_id_info_key_floral_genes %>% 
  knitr::kable()
```

```{r}
# Get the current genes of interest 

list_gene_of_interest <- data.table::fread(table_id_path) %>% 
  dplyr::filter(symbol %in% c("SOC1", "AP1", "AP3", "AGL24", "LFY", "SPL8", "SVP", "SPL5")) %>% 
  dplyr::pull(locus_name) %>% 
  unique()

list_gene_of_interest
```


```{r load_mean_df key floral genes}
b_oleracea_mean_df <- GREAT::load_mean_df(
  file_path_brassica = b_oleracea_path,
  file_path_arabidopsis = ara_path,
  file_path_id_table = table_id_path,
  tissue_wanted = "apex",
  curr_GoIs = list_gene_of_interest,
  sum_brassicas = F
)
```


#### Check if there is genes are missing

```{r}
b_oleracea_mean_df[[1]] %>% 
  dplyr::pull(locus_name) %>% 
  unique()
```

```{r}
missing_genes <- setdiff(table_id_info_key_floral_genes %>% dplyr::pull(CDS.model) %>% toupper(), 
        b_oleracea_mean_df[[1]] %>% dplyr::pull(locus_name) %>% unique())

missing_genes
```

```{r}
# What are they? 

table_id_info_key_floral_genes %>% 
  dplyr::mutate(CDS.model = toupper(CDS.model)) %>% 
  dplyr::filter(CDS.model %in% missing_genes) %>% 
  knitr::kable()
```


```{r check rds}
# Check the data availability from the original RDS
b_oleracea_rds <- readRDS(b_oleracea_path)

setdiff(missing_genes, b_oleracea_rds %>% 
  dplyr::pull(CDS.model) %>% 
  unique())
```

## Specify all parameters


```{r}
do.initial.rescale <- 'TRUE' # should be 'rescale' if want to use scaled df for registration, rather than mean.df
do.register.rescale <- 'rescale' 
outdir.string <- 'TESTING_B_Oleracea_key_floral_genes'

stretch = c(6, 5.5, 5, 4.5, 4, 3.5, 3, 2.5)
min_num_overlapping_points = 4
shift_extreme = 6
transformed.timecourse = 'Col0'
num.shuffled <- 1 
jobNum <- 1
```

```{r echo=FALSE}
# setup flags for rescaling options
if (do.initial.rescale=='rescale') {
  initial.rescale <- TRUE
} else {
  initial.rescale <- FALSE
}
if (do.register.rescale=='rescale') {
  should.rescale <- TRUE
} else {
  should.rescale <- FALSE
}

if (initial.rescale==TRUE) {
  print('********************')
  print('will rescale the data prior to registering, and register using this rescaled mean data!')
  print('********************')
}
if (should.rescale==TRUE){
  print('********************')
  print('will rescale the data when deciding optimal registration!')
  print('********************')
} 
```


```{r include=FALSE}
# directories to save graphs to
real.data.graph.dir <- paste0('graphs/gene_registration/', outdir.string, '_real_data/')
# shuffled.data.graph.dir <- paste0('graphs/gene_registration/', outdir.string, '_shuffled_data/job_', jobNum, '/')
# directories to save real and shuffled expression data to
real.expression.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_data/gene_expression/job_', jobNum, '/')
# shuffled.expression.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_shuffled_data/gene_expression/')
# directories to save real and shuffled distance data to
real.distance.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_distance/job_', jobNum, '/')
# shuffled.distance.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_shuffled_distance/')
  

# somewhere to store the data.tables and graphs
if (!(dir.exists(real.expression.dir))) {
    dir.create(real.expression.dir, recursive=T)
    # dir.create(shuffled.expression.dir, recursive=T)
    
    dir.create(real.distance.dir, recursive=T)
    # dir.create(shuffled.distance.dir, recursive=T)

    dir.create(real.data.graph.dir, recursive=T)
    # dir.create(shuffled.data.graph.dir, recursive=T)
}
```

## Run the shift, stretch data

```{r all}
# just for test
mean.df <- b_oleracea_mean_df[[1]] %>% 
  dplyr::mutate(accession = ifelse(accession == "DH", "Ro18", "Col0"))
all.data.df <- b_oleracea_mean_df[[2]] %>% 
  dplyr::mutate(accession = ifelse(accession == "DH", "Ro18", "Col0"))
```

```{r plot_goI_expression,warning=FALSE}
mean.df_to_plot <- mean.df %>%
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("locus_name" = "CDS.model")) %>% 
  dplyr::rename(bra_gene = locus_name, Ara.id = locus_name.y, Ara.name = symbol)

plot_goI_expression(mean.df_to_plot %>% 
                      dplyr::filter(Ara.name %in% c("AGL24", "SOC1", "AP1", "AP3", "LFY")))
```

```{r}
plot_goI_expression(mean.df_to_plot %>% 
                      dplyr::filter(Ara.name %in% c("AGL24")))
```



```{r}
mean.df_to_plot %>% 
  dplyr::filter(Ara.name == "AGL24", accession == "Ro18")
```




```{r,fig.height=7, fig.width=9, warning=FALSE}
plot_goI_expression(mean.df_to_plot %>% 
                      dplyr::filter(Ara.name %in% c("SPL5", "SPL8", "SVP")))
```


```r
shifted_stretched_all <- prepare_scaled_and_registered_data(
  mean.df, 
  all.data.df,
  stretch, 
  initial.rescale = TRUE, 
  # do_rescale = should.rescale,
  do_rescale = TRUE,
  min_num_overlapping_points,
  shift_extreme, 
  transformed.timecourse
)
```

## Plotting the results

```{r}
imputed_mean_df_shifted_back <- readRDS("intermediate_data/gene_registration/b_oleracea_shifted_to_original_7_14_to_plot.RDS")
imputed_mean_df_shifted_to_brassica <- readRDS("intermediate_data/gene_registration/b_oleracea_from_original_14_14_to_plot.RDS")
```

```{r}
plot_a <- plot_registered_GoIs_for_comparible_timepoints_new(imputed_mean_df_shifted_back) + 
  ggtitle('Delta time shifted back to 7 for Ara, 14 for Bra')
plot_b <- plot_registered_GoIs_for_comparible_timepoints_new(imputed_mean_df_shifted_to_brassica) + 
  ggtitle('Delta time shifted back to 14 for both Ara and Bra')
```

```{r, warning=FALSE, fig.width=11, fig.height=13}
list(plot_a, plot_b) %>%
  patchwork::wrap_plots(ncol = 2, guides = "collect")
```

```{r}
cds_model_wanted <- c("BO2G062650", "BO6G095760", "BO6G108600")
readRDS("intermediate_data/gene_registration/model.comparison_b_oleracea_from_original_14_14.RDS") %>% 
  dplyr::filter(gene %in% cds_model_wanted) %>%
  dplyr::select(gene, stretch, shift) %>% 
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("gene" = "CDS.model")) %>% 
  dplyr::select(symbol, gene, stretch, shift) %>% 
  dplyr::arrange(symbol) 
```

```{r}
readRDS("intermediate_data/gene_registration/model.comparison_shifted_to_original_7_14.RDS") %>% 
  dplyr::filter(gene %in% cds_model_wanted) %>%
  dplyr::select(gene, stretch, shift) %>% 
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("gene" = "CDS.model")) %>% 
  dplyr::select(symbol, gene, stretch, shift) %>% 
  dplyr::arrange(symbol) 
```



### Try to plot shifted AP3 

```{r}
bra_genes_AP1 <- table_id_info_key_floral_genes %>% 
  dplyr::filter(symbol == "AP1") %>% 
  dplyr::pull(CDS.model) %>% 
  toupper()

bra_genes_AP1
```

```{r}
all.shifts <- readRDS("intermediate_data/gene_registration/all.shifts_b_oleracea_from_original_14_14.RDS")
model.comparison.dt <- readRDS("intermediate_data/gene_registration/model.comparison_b_oleracea_from_original_14_14.RDS")

best_shift_stretch_AP3 <- model.comparison.dt %>% 
  dplyr::filter(gene %in% bra_genes_AP3) %>% 
  dplyr::select(gene, stretch, shift)

best_shift_stretch_AP3 %>% 
  knitr::kable()
```

```{r}
AP3_shifted_results <- apply_best_shift(all.data.df, best_shift_stretch_AP3)
```

```{r}
AP3_shifted_results <- AP3_shifted_results %>% 
  dplyr::mutate(accession = ifelse(accession == "Ro18", "DH", "Col"))
```


Plot the results

```{r plot after stretched}
ggplot2::ggplot(AP3_shifted_results[AP3_shifted_results$locus_name=='BO8G083600'])+
  ggplot2::aes(x=shifted.time, y=mean.cpm, color=accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```
```{r}
ggplot2::ggplot(AP3_shifted_results[AP3_shifted_results$locus_name=='BO4G120010'])+
  ggplot2::aes(x=shifted.time, y=mean.cpm, color=accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```



```r
mean_df <- shifted_stretched_all[["mean.df"]] 
mean.df.sc <- shifted_stretched_all[["mean.df.sc"]]
imputed.mean.df <- shifted_stretched_all[["imputed.mean.df"]] 
all.shifts <- shifted_stretched_all[["all.shifts"]] 
model.comparison <- shifted_stretched_all[["model.comparison"]]
```

```r
# Left join to get the symbol genes (e.g. AP3 etc) to the main df
imputed.mean.df_wanted <- imputed.mean.df %>%
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("locus_name" = "CDS.model")) %>% 
  dplyr::select(-c(locus_name.y)) %>%
  dplyr::rename(locus_name = symbol, bra_gene = locus_name)
```


```r}
# registered.plot.df <- imputed.mean.df_wanted
# registered.plot.df <- registered.plot.df[(registered.plot.df$shifted.time >=14),]
test <- imputed.mean.df_wanted %>% 
  dplyr::filter(dplyr::case_when(locus_name == "AGL24" ~ shifted.time >= 14 & shifted.time <= 51, 
                          locus_name == "AP1" ~  shifted.time >= 14 & shifted.time <= 45,
                          locus_name == "AP3" ~  shifted.time >= 14 & shifted.time <= 51,
                          locus_name == "AGL24" ~ shifted.time >= 14 & shifted.time <= 51,
                          locus_name == "LFY" ~ shifted.time >= 14 & shifted.time <= 51,
                          locus_name == "SOC1" ~ shifted.time >= 14 & shifted.time <= 50,
                          locus_name == "SPL8" ~ shifted.time >= 14 & shifted.time <= 45,
                          locus_name == "SPL5" ~ shifted.time >= 14 & shifted.time <= 51,
                          T ~  shifted.time >= 14 & shifted.time <= 40))
```


```r
plot_registered_GoIs_for_comparible_timepoints_new(test)
```



```r
model.comparison %>% 
  # dplyr::filter(gene %in% cds_model_wanted) %>% 
  dplyr::select(gene, stretch, shift) %>% 
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("gene" = "CDS.model")) %>% 
  dplyr::select(symbol, gene, stretch, shift) %>% 
  dplyr::arrange(symbol) 
```




## Debug--------------------------------

### Change accession names

```r
change.accession.names_df <- change.accession.names(mean.df, all.data.df, transformed.timecourse)
```

```r
setdiff(change.accession.names_df[[1]], mean.df)
```
```r
change.accession.names_df[['original.transformed.accession.name']]
change.accession.names_df[['original.other.accession.name']]
```

```r
mean.df.sc <- data.table::copy(mean.df)
mean.df.sc
```

```r
# specify what kind of scaling
# TODO: handle my.scale in conditional
mean.df.sc[, sc.mean.cpm:=scale(mean.cpm, scale=TRUE, center=TRUE), by=.(locus_name, accession)]
mean.df.sc
```

```r
# if rescale == true
to.shift.df <- data.table::copy(mean.df.sc)
to.shift.df$mean.cpm <- to.shift.df$sc.mean.cpm
to.shift.df$sc.mean.cpm <- NULL
# apply THE SAME rescale to all.data.df prior to registration
# TODO: handle my.scale in conditional
all.data.df <- scale_all_rep_data(mean.df, all.data.df, 'scale')
```

```r
to.shift.df 
```


#### Until here is okay ---------

```r
L <- get_best_stretch_and_shift(to.shift.df, all.data.df, stretches = stretch, do_rescale = should.rescale, min_num_overlapping_points, shift_extreme)
```

```r
all_shifts <- L[['all_shifts']]
best_shifts <- L[['best_shifts']]
model.comparison.dt <- L[['model.comparison.dt']]

model.comparison.dt %>% 
  # dplyr::select(-c(seperate.AIC, registered.AIC)) %>%
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("gene" = "CDS.model")) %>% 
  # dplyr::select(symbol, gene, stretch, shift) %>% 
  dplyr::arrange(symbol) 
```


```r
# report model comparison results
model.comparison.dt$BIC.registered.is.better <- (model.comparison.dt$registered.BIC < model.comparison.dt$seperate.BIC)
model.comparison.dt$AIC.registered.is.better <- (model.comparison.dt$registered.AIC < model.comparison.dt$seperate.AIC)
model.comparison.dt$ABIC.registered.is.better <- (model.comparison.dt$BIC.registered.is.better & model.comparison.dt$AIC.registered.is.better)
print("################## Model comparison results #######################")
print(paste0("AIC finds registration better than seperate for :", sum(model.comparison.dt$AIC.registered.is.better), " / ", nrow(model.comparison.dt)))
print(paste0("BIC finds registration better than seperate for :", sum(model.comparison.dt$BIC.registered.is.better), " / ", nrow(model.comparison.dt)))
print(paste0("AIC & BIC finds registration better than seperate for :", sum(model.comparison.dt$ABIC.registered.is.better), " / ", nrow(model.comparison.dt)))
print("###################################################################")
```

```r
model.comparison.dt %>% 
  dplyr::select(-c(seperate.AIC, registered.AIC, AIC.registered.is.better)) %>%
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("gene" = "CDS.model")) %>% 
  # dplyr::select(symbol, gene, stretch, shift) %>% 
  dplyr::arrange(symbol) 
```


```r
shifted.mean.df <- apply_shift_to_registered_genes_only(to.shift.df, best_shifts, model.comparison.dt)
```

```r
locus <- c("Bo4g120010", "Bo8g083600")
shifted.mean.df %>% 
  dplyr::filter(locus_name %in% toupper(locus))
```

```r
imputed.mean.df <- impute_arabidopsis_values(shifted.mean.df)
```

```r
imputed.mean.df %>% 
  dplyr::filter(locus_name %in% toupper(locus))
```

```r
# left join to get the symbol genes (e.g. AP3 etc) to the main df
imputed.mean.df_wanted <- imputed.mean.df %>%
  dplyr::left_join(table_id_info_key_floral_genes %>% 
                     dplyr::mutate(CDS.model = toupper(CDS.model)), by = c("locus_name" = "CDS.model")) %>% 
  dplyr::select(-c(locus_name.y)) %>%
  dplyr::rename(locus_name = symbol, bra_gene = locus_name)
```

```r
plot_registered_GoIs_for_comparible_timepoints(imputed.mean.df_wanted)
```

### Getting extreme shifts

```r
# Make input data name as it is inside the function
test <- mean_df
stretch_factor <- stretch
stretch_factor

curr_sym <- unique(test$locus_name)[2]
curr_sym

test <- test[test$locus_name==curr_sym, ]
# test
```

```r
# transform timepoint to be time from first timepoint
test[, delta_time:=timepoint - min(timepoint), by=.(accession)]
# test
```


```r
ggplot(test[test$locus_name=='BO2G161690',],
       aes(x=delta_time, y=mean.cpm, color=accession))+
  geom_point()+
  geom_line()
```

```r
# apply stretch_factor to the arabidopsis, leave the rapa as is
test$delta_time[test$accession=='Col0'] <- test$delta_time[test$accession=='Col0'] * 6

# test
```


```r
ggplot(test,
       aes(x=delta_time, y=mean.cpm, color=accession))+
  geom_point()+
  geom_line()
```








