---
title: "Running all of gene-registration functions for all genes in B. Oleracea with revision in load_mean_df() function"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set()
library(GREAT)
library(ggplot2)
library(data.table)
library(cowplot)
library(ggpubr)
```

```{r}
plot_registered_GoIs_for_comparible_timepoints <- function(all.stretched.df) {

  registered.plot.df <- all.stretched.df

  registered.plot.df$accession <- as.character(registered.plot.df$accession)
  registered.plot.df$accession[registered.plot.df$accession=='Col0'] <- 'Col-0'
  registered.plot.df$accession[registered.plot.df$accession=='Ro18'] <- 'DH'

  p.registered <- ggplot(registered.plot.df, aes(x=shifted.time, y=mean.cpm, color=accession, fill=accession))+
    stat_summary(fun=mean, geom='line', size=1)+
    stat_summary(fun.data=mean_se, fun.args=list(mult=1),geom='ribbon',
                 color=NA, alpha=0.3)+
    geom_point(size=0.4)+
    theme_bw()+
    xlab('registered time (d)')+
    ylab('normalised expression')+
    facet_wrap(~symbol, scales='free', ncol=2)+
    scale_x_continuous(breaks=scales::pretty_breaks(), limits = c(14, 55))+
    theme(legend.position = 'top',
          legend.title = element_blank(),
          axis.title = element_text(size=10),
          axis.text=element_text(size=6),
          strip.text=element_text(face='italic'),
          legend.margin=margin(21,0,0,0))

  return(p.registered)
}
```


## Load mean data frame

```{r}
# Get all of the data path
table_id_path <- "/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/ID_TAB.csv"
ara_path <- '/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/klepikova.rds'
b_oleracea_path <- "/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/dh_with_sample_id.rds"
```

```{r}
id_table_all <- data.table::fread(table_id_path) %>% 
  dplyr::select(CDS.model, symbol, locus_name) %>% 
  dplyr::arrange(symbol) %>% 
  dplyr::mutate(CDS.model = toupper(CDS.model)) %>% 
  unique()

# Take all locus name from the table
list_all_ara_locus_name <- id_table_all %>% 
  dplyr::pull(locus_name)
```

```{r}
id_table_all %>% 
  head(10) 
```


```r
# Get summary 
id_table_with_symbol <- id_table_all %>% 
  dplyr::filter(symbol != "") %>% 
  nrow()

id_table_without_symbol <- id_table_all %>% 
  dplyr::filter(symbol == "") %>% 
  nrow()

data.frame(with_symbol = id_table_with_symbol, 
           without_symbol = id_table_without_symbol)
```

```{r load_mean_df key floral genes}
b_oleracea_mean_df <- GREAT::load_mean_df(
  file_path_brassica = b_oleracea_path,
  file_path_arabidopsis = ara_path,
  file_path_id_table = table_id_path,
  tissue_wanted = "apex",
  curr_GoIs = list_all_ara_locus_name,
  sum_brassicas = F
)
```

```{r all}
# Change the accession since all the scripts are still hard-coded for "Ro18"
mean_df <- b_oleracea_mean_df[[1]] %>% 
  dplyr::mutate(accession = ifelse(accession == "DH", "Ro18", "Col0"))
all.data.df <- b_oleracea_mean_df[[2]] %>% 
  dplyr::mutate(accession = ifelse(accession == "DH", "Ro18", "Col0"))
```

```{r}
outdir.string <- 'TESTING_B_Oleracea_all_genes'
do.initial.rescale <- 'TRUE' 
do.register.rescale <- 'rescale'

stretch = c(7, 6.5, 6, 5.5, 5, 4.5, 4, 3.5, 3, 2.5)
min.num.overlapping.points = 4
shift.extreme = 4
transformed.timecourse = 'Col0'
num.shuffled <- 1 
jobNum <- 1

if (do.initial.rescale=='rescale') {
  initial.rescale <- TRUE
} else {
  initial.rescale <- FALSE
}
if (do.register.rescale=='rescale') {
  should.rescale <- TRUE
} else {
  should.rescale <- FALSE
}
```


```{r include=FALSE}
# Directories to save graphs to
real.data.graph.dir <- paste0('graphs/gene_registration/', outdir.string, '_real_data/')
real.expression.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_data/gene_expression/job_', jobNum, '/')
real.distance.dir <- paste0('intermediate_data/gene_registration/', outdir.string, '_real_distance/job_', jobNum, '/')

# Somewhere to store the data.tables and graphs
if (!(dir.exists(real.expression.dir))) {
    dir.create(real.expression.dir, recursive=T)
    dir.create(real.distance.dir, recursive=T)
    dir.create(real.data.graph.dir, recursive=T)
}
```

```r
shifted_stretched_all <- prepare_scaled_and_registered_data(
  mean_df, 
  all.data.df,
  stretch, 
  initial.rescale = TRUE, 
  do_rescale = FALSE,
  min.num.overlapping.points,
  shift.extreme, 
  transformed.timecourse
)
```

```{r}
# saveRDS(shifted_stretched_all, "others/shifted_stretched_all.rds")
# 
# shifted_stretched_all[[3]] %>% 
#   nrow()
```

### Analysing 

```{r}
shifted_stretched_all <- readRDS("others/shifted_stretched_all.rds")

mean_df <- shifted_stretched_all[["mean_df"]] 
mean_df.sc <- shifted_stretched_all[["mean_df.sc"]]
imputed.mean_df <- shifted_stretched_all[["imputed.mean_df"]] 
all.shifts <- shifted_stretched_all[["all.shifts"]] 
model.comparison <- shifted_stretched_all[["model.comparison"]]
```

```{r}
model.comparison %>% 
  dplyr::filter(BIC.registered.is.better == FALSE) %>% 
  dplyr::pull(gene) %>% 
  unique() %>% 
  write.csv("/Users/kristiar/PhD/second-rotation-JIC/b_oleracea/data/list_unregistered_gene_ID.csv", row.names = FALSE, col.names = NULL)
```



```{r}
model.comparison %>% 
  head(5)
```

```{r}
data.table(AIC_better = sum(model.comparison$AIC.registered.is.better), 
           BIC_better = sum(model.comparison$BIC.registered.is.better), 
           total_genes = nrow(model.comparison), 
           registered_genes = sum(model.comparison$BIC.registered.is.better), 
           unregistered_genes = nrow(model.comparison) - sum(model.comparison$BIC.registered.is.better))
```

```{r}
table_id_info_key_floral_genes <- data.table::fread(table_id_path) %>% 
  dplyr::filter(symbol %in% c("SOC1", "AP1", "AP3", "AGL24", "LFY", "SPL4", "AGL6", "SPL5", "GA20OX2", "AGL8")) %>% 
  dplyr::select(CDS.model, symbol, locus_name) %>% 
  dplyr::mutate(CDS.model = toupper(CDS.model)) %>% 
  unique() %>% 
  dplyr::arrange(symbol)

table_id_info_key_floral_genes
```

```{r}
imputed.mean_df %>% 
  nrow()
```

### Check the result of key floral genes

```{r}
imputed.mean_df_floral_genes <- imputed.mean_df %>% 
  dplyr::left_join(table_id_info_key_floral_genes, by = c("locus_name" = "CDS.model")) %>% 
  dplyr::filter(!is.na(symbol))
  
imputed.mean_df_floral_genes %>% 
  dplyr::filter(is.registered == TRUE) %>% 
  dplyr::pull(symbol) %>% 
  unique()
```

```{r}
imputed.mean_df_floral_genes %>% 
  dplyr::filter(is.registered == FALSE) %>% 
  dplyr::pull(symbol) %>% 
  unique()
```

```{r}
imputed.mean_df_floral_genes %>% 
  head(5)
```

```{r}
test <- imputed.mean_df_floral_genes %>% 
  dplyr::select(-c(locus_name.y)) %>%
  dplyr::rename(locus_name = symbol, bra_gene = locus_name)
```


```{r, warning=FALSE}
shifted_stretched_oleracea_floral_genes <- plot_registered_GoIs_for_comparible_timepoints(imputed.mean_df_floral_genes)

# ggsave("shifted_stretched_oleracea_floral_genes.pdf", shifted_stretched_oleracea_floral_genes, width = 6, height = 10)


shifted_stretched_oleracea_floral_genes
```

```{r}
imputed.mean_df_floral_genes %>% 
  dplyr::filter(symbol == "AP3") %>% 
  dplyr::pull(locus_name) %>% 
  unique()
  
```

```{r}
model.comparison %>% 
  dplyr::filter(gene %in% c("BO4G120010","BO8G083600"))
```



Try to see example with of non-register models

```{r}
# Get the non-registered genes with known symbol 
imputed.mean_df_non_reg_with_symbol <- imputed.mean_df %>% 
  dplyr::left_join(id_table_all, by = c("locus_name" = "CDS.model")) %>%
  dplyr::filter(is.registered == FALSE, !is.na(symbol)) 

symbol_samples <- imputed.mean_df_non_reg_with_symbol %>% 
  dplyr::pull(symbol) %>% 
  unique() %>% 
  sample(size = 60)

test_symbol <- c("CER1", "CPK7", "EMB506")
```


```{r}
test_using_sample_symbol <- imputed.mean_df_non_reg_with_symbol %>% 
  dplyr::filter(symbol %in% symbol_samples)

test_using_test_symbol <- imputed.mean_df_non_reg_with_symbol %>% 
  dplyr::filter(symbol %in% test_symbol)


test_using_sample_symbol %>% 
  head()
```


```{r, warning=FALSE, fig.width=9, fig.height=50}
plot_registered_GoIs_for_comparible_timepoints(test_using_sample_symbol)
```

```{r, warning=FALSE}
plot_registered_GoIs_for_comparible_timepoints(test_using_test_symbol)
```




