---
title: "Running parameter optimisation parallelly"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Running parameter optimisation parallelly}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, eval=FALSE}
library(greatR)
options(future.rng.onMisuse = "ignore")
```

```{r load-data, eval=FALSE}
# Load data and specify parallelisation parameters
all_data_df <- readRDS(rds_path)
n_workers <- 8
```

```{r run-multisession, eval=FALSE}
# Run registration
future::plan(future::multisession, workers = n_workers)

registration_results <- furrr::future_map(
  .x = results_list,
  .f = function(x) {
    results <- scale_and_register_data(
      input_df = all_data_df,
      # stretches = c(),
      # shifts = c(),
      min_num_overlapping_points = 3,
      initial_rescale = FALSE,
      do_rescale = FALSE,
      accession_data_to_transform = "data_to_transform",
      accession_data_ref = "data_ref",
      maintain_min_num_overlapping_points = TRUE,
      optimise_registration_parameters = TRUE
    ) %>%
      suppressMessages()

    return(results)
  }
)

# Stop multisession plan
future::plan(future::sequential)
```

```{r parse-results, eval=FALSE}
# Parse registration results
registration_summary <- registration_results %>%
  purrr::map(
    ~ purrr::pluck(.x, "model_comparison_df")
  ) %>%
  purrr::reduce(dplyr::bind_rows)
```

