---
title: "Refactoring get_shifts_extreme.R"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set()
# library(GREAT)
load_all()
library(ggplot2)
library(data.table)
library(cowplot)
library(ggpubr)
# 
# source("../../R/get_shifts_extreme.R")
# source("../../R/get_shifts_extreme_copy.R")
```

# Load data 

```{r}
# Define data sample path 

id_table_path <- system.file("extdata/sample_data/id_table_5genes.RDS", package = "GREAT")
arabidopsis_expression_path <- system.file("extdata/sample_data/arabidopsis_expression_5genes.RDS", package = "GREAT")
brassica_rapa_expression_path <- system.file("extdata/sample_data/brassica_rapa_expression_5genes.RDS", package = "GREAT")
```

```{r}
ID_table <- readRDS(id_table_path)
ID_table %>% 
  dplyr::select(CDS.model, position, locus_name, gene_id, symbol) %>% 
  # dplyr::arrange(symbol)
  # dplyr::filter(locus_name %in% c("AT1G69120", "AT5G61850", "AT2G45660")) %>% 
  dplyr::pull(locus_name) %>% 
  unique()
```

```{r}
test_load_mean_df <- load_mean_df(
  filepath_data_fix = brassica_rapa_expression_path,
  filepath_data_to_transform = arabidopsis_expression_path,
  filepath_id_table = id_table_path,
  fix_id_table_shared_colname = "CDS.model",
  fix_and_to_transform_data_shared_colname = "locus_name",
  colnames_id_table = c("CDS.model", "symbol", "locus_name"),
  colnames_wanted = NULL,
  tissue_wanted = "apex",
  curr_GoIs = c("AT4G24540", "AT1G69120", "AT5G61850", "AT2G45660", "AT3G54340"),
  sum_exp_data_fix = F, 
  accession_data_to_transform = "Col0",
  ids_data_fix_colnames = c("CDS.model", "locus_name")
)

test_load_mean_df
```

## get_extreme_shifts_for_all

```{r}
get_extreme_shifts_for_all(
  mean_df = test_load_mean_df[[1]],
  stretch_factor = 2,
  min_num_overlapping_points = 7,
  shift_extreme = 4,
  accession_data_to_transform = "Col0",
  accession_data_fix = "Ro18"
)
```

```{r}
unique(test_load_mean_df$locus_name)
```

```{r}
test_get_best_shift <- get_best_shift(num_shifts = 4,
                           curr_sym = "BRAA02G018970.3C",
                           # curr_sym = "BRAA03G023790.3C",
                           data = test_load_mean_df[[1]],
                           stretch_factor = 1,
                           do_rescale = TRUE,
                           min_shift = 4,
                           max_shift = -4,
                           testing = TRUE,
                           accession_data_to_transform = "Col0",
                           accession_data_fix = "Ro18")
```


```{r}
test_best_shifts <- calculate_all_best_shifts(num_shifts = 10,
                                      mean_df = test_load_mean_df[[1]],
                                      stretch_factor = 1.5,
                                      do_rescale = TRUE,
                                      shift_extreme = 4, 
                                      min_num_overlapping_points = 5, 
                                      testing = FALSE,
                                      accession_data_to_transform = "Col0",
                                      accession_data_fix = "Ro18")

test_best_shifts
```

### test: get_best_result()

```{r}
test_best_shifts[, is_best:=get_best_result(.SD), by=.(gene)]

test_best_shifts

best_shifts <- test_best_shifts[is_best==TRUE,]

best_shifts
```



```{r}
test_load_mean_df[[2]]
```


```{r}
data_after_applying_stretch <- apply_stretch(test_load_mean_df[[2]], 
              best_shifts, 
              accession_data_to_transform = "Col0",
              accession_data_fix = "Ro18",
              data_to_transform_time_added = 11,
              data_fix_time_added = 11)

data_after_applying_stretch
```
### test: apply_best_normalisation()

```{r}
best_shifts$data_transform_compared_mean[best_shifts$gene == "BRAA02G018970.3C"] %>% 
  length()

# Get list of gene
best_shifts$gene %>% unique()

# Get the compared mean from data_tp_transform (Arabidopsis), remember that there is only one copy in Ara, thats why when compared, there are some duplicated 
best_shifts$data_transform_compared_mean
# Take the unique ---------
best_shifts$data_transform_compared_mean %>% unique()
```

```{r}
apply_best_normalisation(data = data_after_applying_stretch,
                                     best_shifts,
                                     accession_data_to_transform = "Col0",
                                     accession_data_fix = "Ro18") 
```



### test: apply_best_shift()

```{r}
test_apply_best_shift <- apply_best_shift(
  data = test_load_mean_df[[2]],
  best_shifts,
  accession_data_to_transform = "Col0",
  accession_data_fix = "Ro18",
  data_to_transform_time_added = 11,
  data_fix_time_added = 11
)

test_apply_best_shift
```

### Test if stretched

```{r}
test <- test_apply_best_shift

test[test$locus_name == "BRAA02G018970.3C"]
```


```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA02G018970.3C" & test$accession == "Col0"]) +
  ggplot2::aes(x = timepoint, y = mean_cpm, color = accession) +
  ggplot2::geom_point()
```

```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA02G018970.3C" & test$accession == "Ro18"]) +
  ggplot2::aes(x = timepoint, y = mean_cpm, color = accession) +
  ggplot2::geom_point()
```

```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA02G018970.3C"]) +
  ggplot2::aes(x = timepoint, y = mean_cpm, color = accession) +
  ggplot2::geom_point()
```


```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA02G018970.3C"]) +
  ggplot2::aes(x = shifted_time, y = mean_cpm, color = accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```


```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA06G025360.3C"]) +
  ggplot2::aes(x = timepoint, y = mean_cpm, color = accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```
```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA06G025360.3C"]) +
  ggplot2::aes(x = shifted_time, y = mean_cpm, color = accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```


##### Plot all of the genes 

```{r}
plot_for_single_gene <- function(gene){
  
 plot <- ggplot2::ggplot(test[test$locus_name == gene]) +
  ggplot2::aes(x = shifted_time, y = mean_cpm, color = accession) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::labs(title = gene)
  
 return(plot)
}

plot_for_single_gene("BRAA06G025360.3C")
```



```{r}
all_gene <- test$locus_name %>% unique()
all_gene[1]

for (gene in 1:length(all_gene)){
  
  print(gene)
  print(all_gene[gene])
  
  gg <- plot_for_single_gene(all_gene[gene])
  print(gg)
}
```

```{r}
# Analyse the replicates in arabidopsis real data
realdat <- test_load_mean_df[[2]] 

ggplot2::ggplot(realdat[realdat$locus_name == "BRAA02G043220.3C" & realdat$accession == "Col0"]) +
  ggplot2::aes(x = timepoint, y = mean_cpm, color = group) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```

```{r}
mean_realdat <- test_load_mean_df[[1]]

mean_realdat[mean_realdat$locus_name == "BRAA02G043220.3C" & mean_realdat$accession == "Col0"] %>% 
  dplyr::arrange(timepoint)
```



```{r}
ggplot2::ggplot(test[test$locus_name == "BRAA02G043220.3C" & test$accession == "Col0"]) +
  ggplot2::aes(x = shifted_time, y = mean_cpm, color = group) +
  ggplot2::geom_point() +
  ggplot2::geom_line()
```

### test: compare_registered_to_unregistered_model()

```{r}
# Test one of AP1 copy in B. rapa with locus_name "BRAA02G018970.3C" and AGL24 "BRAA03G051930.3C"
L <- compare_registered_to_unregistered_model(
  curr_sym = "BRAA03G051930.3C",
  all_data_df = test_apply_best_shift
)

L[["separate.AIC"]]
```

```{r}
ggplot2::ggplot(curr_data_df) +
  ggplot2::aes(x = shifted_time, y = mean_cpm, shape = is_compared, color = accession) +
  ggplot2::geom_point()
```

### test: calculate_all_model_comparison_stats()

```{r}
calculate_all_model_comparison_stats(
  test_load_mean_df[[2]],
  best_shifts,
  accession_data_to_transform = "Col0",
  accession_data_fix = "Ro18",
  data_to_transform_time_added = 11,
  data_fix_time_added = 11
)
```


