---
title: "Info data"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set()

load_all()
library(ggplot2)
library(data.table)
library(dplyr)
```

# Load data 

```{r}
# Define data sample path 

id_table_path <- system.file("extdata/sample_data/id_table_5genes.RDS", package = "GREAT")
arabidopsis_expression_path <- system.file("extdata/sample_data/arabidopsis_expression_5genes.RDS", package = "GREAT")
brassica_rapa_expression_path <- system.file("extdata/sample_data/brassica_rapa_expression_5genes.RDS", package = "GREAT")
```

```{r}
ID_table <- readRDS(id_table_path)
ID_table %>% 
  dplyr::select(CDS.model, position, locus_name, gene_id, symbol) %>% 
  # dplyr::arrange(symbol)
  # dplyr::filter(locus_name %in% c("AT1G69120", "AT5G61850", "AT2G45660")) %>% 
  dplyr::pull(locus_name) %>% 
  unique()


ID_table %>% dplyr::filter(symbol == "AP1")
```

```{r}
readRDS(brassica_rapa_expression_path)
```



```{r}
test_load_mean_df <- load_mean_df(
  filepath_data_fix = brassica_rapa_expression_path,
  filepath_data_to_transform = arabidopsis_expression_path,
  filepath_id_table = id_table_path,
  fix_id_table_shared_colname = "CDS.model",
  fix_and_to_transform_data_shared_colname = "locus_name",
  colnames_id_table = c("CDS.model", "symbol", "locus_name"),
  colnames_wanted = NULL,
  tissue_wanted = "apex",
  curr_GoIs = c("AT4G24540", "AT1G69120", "AT5G61850", "AT2G45660", "AT3G54340"),
  sum_exp_data_fix = F, 
  accession_data_to_transform = "Col0",
  ids_data_fix_colnames = c("CDS.model", "locus_name")
)

test_load_mean_df %>% saveRDS("../../../../Downloads/test_data.RDS")
```
