---
title: "Comparing original to refactored functions"
output: 
  github_document:
    toc: true
---

```{r setup}
knitr::opts_chunk$set()

load_all()
library(ggplot2)
library(data.table)
library(cowplot)
library(ggpubr)

# source("../../dev/code_registration_from_paper/registration/registration_functions.R")
```

## Data provided in Alex's paper 

```{r}
path_data <- "../../dev/code_registration_from_paper/registration/data_for_registration.rds"

alex_data <- readRDS(path_data)
```

```{r}
alex_data[[1]] %>% 
  dplyr::filter(accession != "Ro18")
```

### Mapped alex data with table ID I have

```{r}
# Define data sample path 

id_table_path <- system.file("extdata/sample_data/id_table_5genes.RDS", package = "GREAT")

ID_table <- readRDS(id_table_path)

ID_table <- ID_table %>% 
  dplyr::select(CDS.model, position, locus_name, gene_id, symbol)

bra_acc <- ID_table %>% 
  dplyr::pull(CDS.model) %>% 
  unique()
```

```{r}
filtered_alex_data_mean <- alex_data[[1]] %>% 
  dplyr::filter(locus_name %in% bra_acc)

filtered_alex_data_all <- alex_data[[2]] %>% 
  dplyr::filter(locus_name %in% bra_acc)

filtered_alex_data_mean
```



```{r}
# Load data obtained from Ruth's refactored function
path_b_rapa <- "~/Downloads/test_data.RDS"

alex_data_mean <- readRDS(path_b_rapa)[[1]]
alex_data_all <- readRDS(path_b_rapa)[[2]]
# ruth_data
```

```{r}
setdiff(filtered_alex_data_mean, ruth_data_mean)
```

Conclusion: same data to begin with....

```{r}
L <- get_best_stretch_and_shift_alex(to.shift.df = filtered_alex_data_mean, 
                                all.data.df = filtered_alex_data_all, 
                                stretches = c(2, 1.5, 1), 
                                do.rescale = TRUE, 
                                min.num.overlapping.points = 4, 
                                shift.extreme = 4)
all_shifts_alex <- L[['all_shifts']]
best_shifts_alex <- L[['best_shifts']]
model.comparison.dalex <- L[['model.comparison.dt']]
```

```{r}
L_ruth <- GREAT::get_best_stretch_and_shift(to_shift_df = ruth_data_mean,
                                       all_data_df = ruth_data_all,
                                       stretches = c(2, 1.5, 1),
                                       do_rescale = TRUE,
                                       min_num_overlapping_points = 4,
                                       shift_extreme = 4,
                                       num_shifts = 27,
                                       testing = FALSE,
                                       accession_data_to_transform = "Col0",
                                       accession_data_fix = "Ro18",
                                       data_to_transform_time_added = 11,
                                       data_fix_time_added = 11)

all_shifts_ruth <- L_ruth[['all_shifts']]
best_shifts_ruth <- L_ruth[['best_shifts']]
model.comparison.dt_ruth <- L_ruth[['model_comparison_dt']]
```

```{r}
diffdf::diffdf(
  all_shifts_alex %>% 
    `colnames<-`(colnames(all_shifts_ruth)),
  all_shifts_ruth
)
```

```{r}
diffdf::diffdf(
 best_shifts_alex %>% 
    `colnames<-`(colnames(best_shifts_ruth)),
  best_shifts_ruth
)
```

```{r}
diffdf::diffdf(
model.comparison.dalex %>% 
    `colnames<-`(colnames(model.comparison.dt_ruth)),
 model.comparison.dt_ruth
)
```

### Finding difference now in reporting model comparison results

```{r}
model.comparison.dalex$BIC.registered.is.better <- (model.comparison.dalex$registered.BIC < model.comparison.dalex$seperate.BIC)
model.comparison.dalex$AIC.registered.is.better <- (model.comparison.dalex$registered.AIC < model.comparison.dalex$seperate.AIC)
model.comparison.dalex$ABIC.registered.is.better <- (model.comparison.dalex$BIC.registered.is.better & model.comparison.dalex$AIC.registered.is.better)
print('################## Model comparison results #######################')
print(paste0('AIC finds registration better than seperate for :', sum(model.comparison.dalex$AIC.registered.is.better), ' / ', nrow(model.comparison.dalex)))
print(paste0('BIC finds registration better than seperate for :', sum(model.comparison.dalex$BIC.registered.is.better), ' / ', nrow(model.comparison.dalex)))
print(paste0('AIC & BIC finds registration better than seperate for :', sum(model.comparison.dalex$ABIC.registered.is.better), ' / ', nrow(model.comparison.dalex)))
print('###################################################################')
```

```{r}
# Add columns which flags which BIC and AIC values are better
model.comparison.dt_ruth$BIC_registered_is_better <- (model.comparison.dt_ruth$registered.BIC < model.comparison.dt_ruth$separate.BIC)
model.comparison.dt_ruth$AIC_registered_is_better <- (model.comparison.dt_ruth$registered.AIC < model.comparison.dt_ruth$separate.AIC)
model.comparison.dt_ruth$ABIC_registered_is_better <- (model.comparison.dt_ruth$BIC_registered_is_better & model.comparison.dt_ruth$AIC_registered_is_better)


# Report model comparison results
print("################## Model comparison results #######################")
print(paste0("AIC finds registration better than separate for :", sum(model.comparison.dt_ruth$AIC_registered_is_better), " / ", nrow(model.comparison.dt_ruth)))
print(paste0("BIC finds registration better than separate for :", sum(model.comparison.dt_ruth$BIC_registered_is_better), " / ", nrow(model.comparison.dt_ruth)))
print(paste0("AIC & BIC finds registration better than separate for :", sum(model.comparison.dt_ruth$ABIC_registered_is_better), " / ", nrow(model.comparison.dt_ruth)))
print("###################################################################")
```

### NOw comparing function: apply_shift_to_registered_genes_only

```{r}
shifted.mean.df_alex <- apply_shift_to_registered_genes_only_alex(filtered_alex_data_mean, best_shifts_alex, model.comparison.dalex)
```

```{r}
shifted_mean_df_ruth <- GREAT::apply_shift_to_registered_genes_only(to_shift_df = ruth_data_mean,
                                                          best_shifts = best_shifts_ruth,
                                                          model_comparison_dt = model.comparison.dt_ruth,
                                                          accession_data_to_transform = "Col0",
                                                          accession_data_fix = "Ro18",
                                                          data_to_transform_time_added = 11,
                                                          data_fix_time_added = 11)
```

```{r}
diffdf::diffdf(
  shifted.mean.df_alex %>% 
    `colnames<-`(colnames(shifted_mean_df_ruth)),
 shifted_mean_df_ruth
)
```
```{r}
shifted.mean.df_alex
```
```{r}
shifted_mean_df_ruth
```

### Test func: impute_arabidopsis_value

```{r}
imputed.mean.df_alex <- impute_arabidopsis_values_alex(shifted.mean.df_alex)
```

```{r}
imputed_mean_df_ruth <- impute_transformed_exp_values(shifted_mean_df = shifted_mean_df_ruth,
                                               accession_data_to_transform = "Col0",
                                               accession_data_fix = "Ro18")
```


```{r}
diffdf::diffdf(
 imputed.mean.df_alex %>% 
    `colnames<-`(colnames(imputed_mean_df_ruth)),
  imputed_mean_df_ruth
)
```



